<?php

$heroes = array(
    0 => array(
        "name_raw" => "blank",
        "name_formatted" => "No Hero",
        "pic" => "aaa_blank",
    ),
    1 => array(
        "name_raw" => "npc_dota_hero_antimage",
        "name_formatted" => "Anti-Mage",
        "pic" => "anti-mage",
    ),
    2 => array(
        "name_raw" => "npc_dota_hero_axe",
        "name_formatted" => "Axe",
        "pic" => "axe",
        "pic_1" => "archive/axe-old-1",
        "pic_retro" => "archive/axe-old-1",
    ),
    3 => array(
        "name_raw" => "npc_dota_hero_bane",
        "name_formatted" => "Bane",
        "pic" => "bane",
        "pic_1" => "archive/bane-old-1",
        "pic_retro" => "archive/bane-old-1",
    ),
    4 => array(
        "name_raw" => "npc_dota_hero_bloodseeker",
        "name_formatted" => "Bloodseeker",
        "pic" => "bloodseeker",
    ),
    5 => array(
        "name_raw" => "npc_dota_hero_crystal_maiden",
        "name_formatted" => "Crystal Maiden",
        "pic" => "crystal-maiden",
    ),
    6 => array(
        "name_raw" => "npc_dota_hero_drow_ranger",
        "name_formatted" => "Drow Ranger",
        "pic" => "drow-ranger",
        "pic_1" => "archive/drow-ranger-old-1",
        "pic_retro" => "archive/drow-ranger-old-1",
    ),
    7 => array(
        "name_raw" => "npc_dota_hero_earthshaker",
        "name_formatted" => "Earthshaker",
        "pic" => "earthshaker",
        "pic_1" => "archive/earthshaker-old-1",
        "pic_retro" => "archive/earthshaker-old-1",
    ),
    8 => array(
        "name_raw" => "npc_dota_hero_juggernaut",
        "name_formatted" => "Juggernaut",
        "pic" => "juggernaut",
        "pic_1" => "archive/juggernaut-old-1",
        "pic_retro" => "archive/juggernaut-old-1",
    ),
    9 => array(
        "name_raw" => "npc_dota_hero_mirana",
        "name_formatted" => "Mirana",
        "pic" => "mirana",
    ),
    10 => array(
        "name_raw" => "npc_dota_hero_morphling",
        "name_formatted" => "Morphling",
        "pic" => "morphling",
    ),
    11 => array(
        "name_raw" => "npc_dota_hero_nevermore",
        "name_formatted" => "Shadow Fiend",
        "pic" => "shadow-fiend",
        "pic_1" => "archive/shadow-fiend-old-1",
        "pic_2" => "archive/shadow-fiend-old-2",
        "pic_3" => "archive/shadow-fiend-old-3",
        "pic_retro" => "archive/shadow-fiend-old-3",
    ),
    12 => array(
        "name_raw" => "npc_dota_hero_phantom_lancer",
        "name_formatted" => "Phantom Lancer",
        "pic" => "phantom-lancer",
        "pic_1" => "archive/phantom-lancer-old-1",
        "pic_2" => "archive/phantom-lancer-old-2",
        "pic_retro" => "archive/phantom-lancer-old-2",
    ),
    13 => array(
        "name_raw" => "npc_dota_hero_puck",
        "name_formatted" => "Puck",
        "pic" => "puck",
        "pic_1" => "archive/puck-old-1",
        "pic_retro" => "archive/puck-old-1",
    ),
    14 => array(
        "name_raw" => "npc_dota_hero_pudge",
        "name_formatted" => "Pudge",
        "pic" => "pudge",
        "pic_1" => "archive/pudge-old-1",
        "pic_retro" => "archive/pudge-old-1",
    ),
    15 => array(
        "name_raw" => "npc_dota_hero_razor",
        "name_formatted" => "Razor",
        "pic" => "razor",
    ),
    16 => array(
        "name_raw" => "npc_dota_hero_sand_king",
        "name_formatted" => "Sand King",
        "pic" => "sand-king",
    ),
    17 => array(
        "name_raw" => "npc_dota_hero_storm_spirit",
        "name_formatted" => "Storm Spirit",
        "pic" => "storm-spirit",
        "pic_1" => "archive/storm-spirit-old-1",
        "pic_retro" => "archive/storm-spirit-old-1",
    ),
    18 => array(
        "name_raw" => "npc_dota_hero_sven",
        "name_formatted" => "Sven",
        "pic" => "sven",
    ),
    19 => array(
        "name_raw" => "npc_dota_hero_tiny",
        "name_formatted" => "Tiny",
        "pic" => "tiny",
    ),
    20 => array(
        "name_raw" => "npc_dota_hero_vengefulspirit",
        "name_formatted" => "Vengeful Spirit",
        "pic" => "vengeful-spirit",
        "pic_1" => "archive/vengeful-spirit-old-1",
        "pic_2" => "archive/vengeful-spirit-old-2",
        "pic_retro" => "archive/vengeful-spirit-old-2",
    ),
    21 => array(
        "name_raw" => "npc_dota_hero_windrunner",
        "name_formatted" => "Wind Runner",
        "pic" => "windranger",
        "pic_1" => "archive/windranger-old-1",
        "pic_retro" => "archive/windranger-old-1",
    ),
    22 => array(
        "name_raw" => "npc_dota_hero_zuus",
        "name_formatted" => "Zeus",
        "pic" => "zeus",
        "pic_1" => "archive/zeus-old-1",
        "pic_retro" => "archive/zeus-old-1",
    ),
    23 => array(
        "name_raw" => "npc_dota_hero_kunkka",
        "name_formatted" => "Kunkka",
        "pic" => "kunkka",
    ),
    25 => array(
        "name_raw" => "npc_dota_hero_lina",
        "name_formatted" => "Lina",
        "pic" => "lina",
    ),
    26 => array(
        "name_raw" => "npc_dota_hero_lion",
        "name_formatted" => "Lion",
        "pic" => "lion",
        "pic_1" => "archive/lion-old-1",
        "pic_2" => "archive/lion-old-2",
        "pic_3" => "archive/lion-old-3",
        "pic_4" => "archive/lion-old-4",
        "pic_retro" => "archive/lion-old-4",
    ),
    27 => array(
        "name_raw" => "npc_dota_hero_shadow_shaman",
        "name_formatted" => "Shadow Shaman",
        "pic" => "shadow-shaman",
    ),
    28 => array(
        "name_raw" => "npc_dota_hero_slardar",
        "name_formatted" => "Slardar",
        "pic" => "slardar",
    ),
    29 => array(
        "name_raw" => "npc_dota_hero_tidehunter",
        "name_formatted" => "Tidehunter",
        "pic" => "tidehunter",
    ),
    30 => array(
        "name_raw" => "npc_dota_hero_witch_doctor",
        "name_formatted" => "Witch Doctor",
        "pic" => "witch-doctor",
        "pic_1" => "archive/witch-doctor-old-1",
        "pic_2" => "archive/witch-doctor-old-2",
        "pic_retro" => "archive/witch-doctor-old-2",
    ),
    31 => array(
        "name_raw" => "npc_dota_hero_lich",
        "name_formatted" => "Lich",
        "pic" => "lich",
    ),
    32 => array(
        "name_raw" => "npc_dota_hero_riki",
        "name_formatted" => "Riki",
        "pic" => "riki",
        "pic_1" => "archive/riki-old-1",
        "pic_2" => "archive/riki-old-2",
        "pic_retro" => "archive/riki-old-2",
    ),
    33 => array(
        "name_raw" => "npc_dota_hero_enigma",
        "name_formatted" => "Enigma",
        "pic" => "enigma",
    ),
    34 => array(
        "name_raw" => "npc_dota_hero_tinker",
        "name_formatted" => "Tinker",
        "pic" => "tinker",
    ),
    35 => array(
        "name_raw" => "npc_dota_hero_sniper",
        "name_formatted" => "Sniper",
        "pic" => "sniper",
        "pic_1" => "archive/sniper-old-1",
        "pic_2" => "archive/sniper-old-2",
        "pic_retro" => "archive/sniper-old-2",
    ),
    36 => array(
        "name_raw" => "npc_dota_hero_necrolyte",
        "name_formatted" => "Necrophos",
        "pic" => "necrophos",
    ),
    37 => array(
        "name_raw" => "npc_dota_hero_warlock",
        "name_formatted" => "Warlock",
        "pic" => "warlock",
        "pic_1" => "archive/warlock-old-1",
        "pic_retro" => "archive/warlock-old-1",
    ),
    38 => array(
        "name_raw" => "npc_dota_hero_beastmaster",
        "name_formatted" => "Beastmaster",
        "pic" => "beastmaster",
        "pic_1" => "archive/beastmaster-old-1",
        "pic_2" => "archive/beastmaster-old-2",
        "pic_retro" => "archive/beastmaster-old-2",
    ),
    39 => array(
        "name_raw" => "npc_dota_hero_queenofpain",
        "name_formatted" => "Queen of Pain",
        "pic" => "queen-of-pain",
        "pic_1" => "archive/queen-of-pain-old-1",
        "pic_2" => "archive/queen-of-pain-old-2",
        "pic_3" => "archive/queen-of-pain-old-3",
        "pic_retro" => "archive/queen-of-pain-old-3",
    ),
    40 => array(
        "name_raw" => "npc_dota_hero_venomancer",
        "name_formatted" => "Venomancer",
        "pic" => "venomancer",
        "pic_1" => "archive/venomancer-old-1",
        "pic_retro" => "archive/venomancer-old-1",
    ),
    41 => array(
        "name_raw" => "npc_dota_hero_faceless_void",
        "name_formatted" => "Faceless Void",
        "pic" => "faceless-void",
        "pic_1" => "archive/faceless-void-old-1",
        "pic_2" => "archive/faceless-void-old-2",
        "pic_retro" => "archive/faceless-void-old-2",
    ),
    42 => array(
        "name_raw" => "npc_dota_hero_skeleton_king",
        "name_formatted" => "Skeleton King",
        "pic" => "skeleton-king",
        "pic_1" => "archive/skeleton-king-old-1",
        "pic_retro" => "archive/skeleton-king-old-1",
    ),
    43 => array(
        "name_raw" => "npc_dota_hero_death_prophet",
        "name_formatted" => "Death Prophet",
        "pic" => "death-prophet",
        "pic_1" => "archive/death-prophet-old-1",
        "pic_2" => "archive/death-prophet-old-2",
        "pic_3" => "archive/death-prophet-old-3",
        "pic_retro" => "archive/death-prophet-old-3",
    ),
    44 => array(
        "name_raw" => "npc_dota_hero_phantom_assassin",
        "name_formatted" => "Phantom Assassin",
        "pic" => "phantom-assassin",
        "pic_1" => "archive/phantom-assassin-old-1",
        "pic_2" => "archive/phantom-assassin-old-2",
        "pic_3" => "archive/phantom-assassin-old-3",
        "pic_4" => "archive/phantom-assassin-old-4",
        "pic_retro" => "archive/phantom-assassin-old-4",
    ),
    45 => array(
        "name_raw" => "npc_dota_hero_pugna",
        "name_formatted" => "Pugna",
        "pic" => "pugna",
    ),
    46 => array(
        "name_raw" => "npc_dota_hero_templar_assassin",
        "name_formatted" => "Templar Assassin",
        "pic" => "templar-assassin",
        "pic_1" => "archive/templar-assassin-old-1",
        "pic_2" => "archive/templar-assassin-old-2",
        "pic_retro" => "archive/templar-assassin-old-2",
    ),
    47 => array(
        "name_raw" => "npc_dota_hero_viper",
        "name_formatted" => "Viper",
        "pic" => "viper",
    ),
    48 => array(
        "name_raw" => "npc_dota_hero_luna",
        "name_formatted" => "Luna",
        "pic" => "luna",
        "pic_1" => "archive/luna-old-1",
        "pic_2" => "archive/luna-old-2",
        "pic_retro" => "archive/luna-old-2",
    ),
    49 => array(
        "name_raw" => "npc_dota_hero_dragon_knight",
        "name_formatted" => "Dragon Knight",
        "pic" => "dragon-knight",
        "pic_1" => "archive/dragon-knight-old-1",
        "pic_retro" => "archive/dragon-knight-old-1",
    ),
    50 => array(
        "name_raw" => "npc_dota_hero_dazzle",
        "name_formatted" => "Dazzle",
        "pic" => "dazzle",
        "pic_1" => "archive/dazzle-old-1",
        "pic_retro" => "archive/dazzle-old-1",
    ),
    51 => array(
        "name_raw" => "npc_dota_hero_rattletrap",
        "name_formatted" => "Clockwerk",
        "pic" => "clockwerk",
    ),
    52 => array(
        "name_raw" => "npc_dota_hero_leshrac",
        "name_formatted" => "Leshrac",
        "pic" => "leshrac",
    ),
    53 => array(
        "name_raw" => "npc_dota_hero_furion",
        "name_formatted" => "Nature's Prophet",
        "pic" => "natures-prophet",
    ),
    54 => array(
        "name_raw" => "npc_dota_hero_life_stealer",
        "name_formatted" => "Lifestealer",
        "pic" => "lifestealer",
        "pic_1" => "archive/lifestealer-old-1",
        "pic_retro" => "archive/lifestealer-old-1",
    ),
    55 => array(
        "name_raw" => "npc_dota_hero_dark_seer",
        "name_formatted" => "Dark Seer",
        "pic" => "dark-seer",
    ),
    56 => array(
        "name_raw" => "npc_dota_hero_clinkz",
        "name_formatted" => "Clinkz",
        "pic" => "clinkz",
        "pic_1" => "archive/clinkz-old-1",
        "pic_retro" => "archive/clinkz-old-1",
    ),
    57 => array(
        "name_raw" => "npc_dota_hero_omniknight",
        "name_formatted" => "Omniknight",
        "pic" => "omniknight",
        "pic_1" => "archive/omniknight-old-1",
        "pic_2" => "archive/omniknight-old-2",
        "pic_retro" => "archive/omniknight-old-2",
    ),
    58 => array(
        "name_raw" => "npc_dota_hero_enchantress",
        "name_formatted" => "Enchantress",
        "pic" => "enchantress",
        "pic_1" => "archive/enchantress-old-1",
        "pic_2" => "archive/enchantress-old-2",
        "pic_retro" => "archive/enchantress-old-2",
    ),
    59 => array(
        "name_raw" => "npc_dota_hero_huskar",
        "name_formatted" => "Huskar",
        "pic" => "huskar",
        "pic_1" => "archive/huskar-old-1",
        "pic_retro" => "archive/huskar-old-1",
    ),
    60 => array(
        "name_raw" => "npc_dota_hero_night_stalker",
        "name_formatted" => "Night Stalker",
        "pic" => "night-stalker",
    ),
    61 => array(
        "name_raw" => "npc_dota_hero_broodmother",
        "name_formatted" => "Broodmother",
        "pic" => "broodmother",
        "pic_1" => "archive/broodmother-old-1",
        "pic_2" => "archive/broodmother-old-2",
        "pic_retro" => "archive/broodmother-old-2",
    ),
    62 => array(
        "name_raw" => "npc_dota_hero_bounty_hunter",
        "name_formatted" => "Bounty Hunter",
        "pic" => "bounty-hunter",
        "pic_1" => "archive/bounty-hunter-old-1",
        "pic_2" => "archive/bounty-hunter-old-2",
        "pic_retro" => "archive/bounty-hunter-old-2",
    ),
    63 => array(
        "name_raw" => "npc_dota_hero_weaver",
        "name_formatted" => "Weaver",
        "pic" => "weaver",
    ),
    64 => array(
        "name_raw" => "npc_dota_hero_jakiro",
        "name_formatted" => "Jakiro",
        "pic" => "jakiro",
        "pic_1" => "archive/jakiro-old-1",
        "pic_retro" => "archive/jakiro-old-1",
    ),
    65 => array(
        "name_raw" => "npc_dota_hero_batrider",
        "name_formatted" => "Batrider",
        "pic" => "batrider",
        "pic_1" => "archive/batrider-old-1",
        "pic_retro" => "archive/batrider-old-1",
    ),
    66 => array(
        "name_raw" => "npc_dota_hero_chen",
        "name_formatted" => "Chen",
        "pic" => "chen",
        "pic_1" => "archive/chen-old-1",
        "pic_retro" => "archive/chen-old-1",
    ),
    67 => array(
        "name_raw" => "npc_dota_hero_spectre",
        "name_formatted" => "Spectre",
        "pic" => "spectre",
    ),
    68 => array(
        "name_raw" => "npc_dota_hero_ancient_apparition",
        "name_formatted" => "Ancient Apparition",
        "pic" => "ancient-apparition",
    ),
    69 => array(
        "name_raw" => "npc_dota_hero_doom_bringer",
        "name_formatted" => "Doom",
        "pic" => "doom",
    ),
    70 => array(
        "name_raw" => "npc_dota_hero_ursa",
        "name_formatted" => "Ursa",
        "pic" => "ursa",
        "pic_1" => "archive/ursa-old-1",
        "pic_retro" => "archive/ursa-old-1",
    ),
    71 => array(
        "name_raw" => "npc_dota_hero_spirit_breaker",
        "name_formatted" => "Spirit Breaker",
        "pic" => "spirit-breaker",
    ),
    72 => array(
        "name_raw" => "npc_dota_hero_gyrocopter",
        "name_formatted" => "Gyrocopter",
        "pic" => "gyrocopter",
        "pic_1" => "archive/gyrocopter-old-1",
        "pic_2" => "archive/gyrocopter-old-2",
        "pic_retro" => "archive/gyrocopter-old-2",
    ),
    73 => array(
        "name_raw" => "npc_dota_hero_alchemist",
        "name_formatted" => "Alchemist",
        "pic" => "alchemist",
    ),
    74 => array(
        "name_raw" => "npc_dota_hero_invoker",
        "name_formatted" => "Invoker",
        "pic" => "invoker",
        "pic_1" => "archive/invoker-old-1",
        "pic_retro" => "archive/invoker-old-1",
    ),
    75 => array(
        "name_raw" => "npc_dota_hero_silencer",
        "name_formatted" => "Silencer",
        "pic" => "silencer",
        "pic_1" => "archive/silencer-old-1",
        "pic_2" => "archive/silencer-old-2",
        "pic_3" => "archive/silencer-old-3",
        "pic_retro" => "archive/silencer-old-3",
    ),
    76 => array(
        "name_raw" => "npc_dota_hero_obsidian_destroyer",
        "name_formatted" => "Outworld Devourer",
        "pic" => "outworld-devourer",
    ),
    77 => array(
        "name_raw" => "npc_dota_hero_lycan",
        "name_formatted" => "Lycan",
        "pic" => "lycan",
        "pic_1" => "archive/lycan-old-1",
        "pic_retro" => "archive/lycan-old-1",
    ),
    78 => array(
        "name_raw" => "npc_dota_hero_brewmaster",
        "name_formatted" => "Brewmaster",
        "pic" => "brewmaster",
        "pic_1" => "archive/brewmaster-old-1",
        "pic_2" => "archive/brewmaster-old-2",
        "pic_3" => "archive/brewmaster-old-3",
        "pic_4" => "archive/brewmaster-old-4",
        "pic_retro" => "archive/brewmaster-old-4",
    ),
    79 => array(
        "name_raw" => "npc_dota_hero_shadow_demon",
        "name_formatted" => "Shadow Demon",
        "pic" => "shadow-demon",
    ),
    80 => array(
        "name_raw" => "npc_dota_hero_lone_druid",
        "name_formatted" => "Lone Druid",
        "pic" => "lone-druid",
        "pic_1" => "archive/lone-druid-old-1",
        "pic_2" => "archive/lone-druid-old-2",
        "pic_3" => "archive/lone-druid-old-3",
        "pic_retro" => "archive/lone-druid-old-3",
    ),
    81 => array(
        "name_raw" => "npc_dota_hero_chaos_knight",
        "name_formatted" => "Chaos Knight",
        "pic" => "chaos-knight",
        "pic_1" => "archive/chaos-knight-old-1",
        "pic_2" => "archive/chaos-knight-old-2",
        "pic_3" => "archive/chaos-knight-old-3",
        "pic_retro" => "archive/chaos-knight-old-3",
    ),
    82 => array(
        "name_raw" => "npc_dota_hero_meepo",
        "name_formatted" => "Meepo",
        "pic" => "meepo",
        "pic_1" => "archive/meepo-old-1",
        "pic_2" => "archive/meepo-old-2",
        "pic_3" => "archive/meepo-old-3",
        "pic_4" => "archive/meepo-old-4",
        "pic_5" => "archive/meepo-old-5",
        "pic_retro" => "archive/meepo-old-5",
    ),
    83 => array(
        "name_raw" => "npc_dota_hero_treant",
        "name_formatted" => "Treant Protector",
        "pic" => "treant-protector",
        "pic_1" => "archive/treant-protector-old-1",
        "pic_2" => "archive/treant-protector-old-2",
        "pic_retro" => "archive/treant-protector-old-2",
    ),
    84 => array(
        "name_raw" => "npc_dota_hero_ogre_magi",
        "name_formatted" => "Ogre Magi",
        "pic" => "ogre-magi",
        "pic_1" => "archive/ogre-magi-old-1",
        "pic_2" => "archive/ogre-magi-old-2",
        "pic_retro" => "archive/ogre-magi-old-2",
    ),
    85 => array(
        "name_raw" => "npc_dota_hero_undying",
        "name_formatted" => "Undying",
        "pic" => "undying",
        "pic_1" => "archive/undying-old-1",
        "pic_2" => "archive/undying-old-2",
        "pic_retro" => "archive/undying-old-2",
    ),
    86 => array(
        "name_raw" => "npc_dota_hero_rubick",
        "name_formatted" => "Rubick",
        "pic" => "rubick",
        "pic_1" => "archive/rubick-old-1",
        "pic_retro" => "archive/rubick-old-1",
    ),
    87 => array(
        "name_raw" => "npc_dota_hero_disruptor",
        "name_formatted" => "Disruptor",
        "pic" => "disruptor",
        "pic_1" => "archive/disruptor-old-1",
        "pic_2" => "archive/disruptor-old-2",
        "pic_retro" => "archive/disruptor-old-2",
    ),
    88 => array(
        "name_raw" => "npc_dota_hero_nyx_assassin",
        "name_formatted" => "Nyx Assassin",
        "pic" => "nyx-assassin",
        "pic_1" => "archive/nyx-assassin-old-1",
        "pic_2" => "archive/nyx-assassin-old-2",
        "pic_retro" => "archive/nyx-assassin-old-2",
    ),
    89 => array(
        "name_raw" => "npc_dota_hero_naga_siren",
        "name_formatted" => "Naga Siren",
        "pic" => "naga-siren",
        "pic_1" => "archive/naga-siren-old-1",
        "pic_2" => "archive/naga-siren-old-2",
        "pic_retro" => "archive/naga-siren-old-2",
    ),
    90 => array(
        "name_raw" => "npc_dota_hero_keeper_of_the_light",
        "name_formatted" => "Keeper of the Light",
        "pic" => "keeper-of-the-light",
        "pic_1" => "archive/keeper-of-the-light-old-1",
        "pic_retro" => "archive/keeper-of-the-light-old-1",
    ),
    91 => array(
        "name_raw" => "npc_dota_hero_wisp",
        "name_formatted" => "Wisp",
        "pic" => "wisp",
        "pic_1" => "archive/wisp-old-1",
        "pic_retro" => "archive/wisp-old-1",
    ),
    92 => array(
        "name_raw" => "npc_dota_hero_visage",
        "name_formatted" => "Visage",
        "pic" => "visage",
        "pic_1" => "archive/visage-old-1",
        "pic_retro" => "archive/visage-old-1",
    ),
    93 => array(
        "name_raw" => "npc_dota_hero_slark",
        "name_formatted" => "Slark",
        "pic" => "slark",
    ),
    94 => array(
        "name_raw" => "npc_dota_hero_medusa",
        "name_formatted" => "Medusa",
        "pic" => "medusa",
        "pic_1" => "archive/medusa-old-1",
        "pic_2" => "archive/medusa-old-2",
        "pic_retro" => "archive/medusa-old-2",
    ),
    95 => array(
        "name_raw" => "npc_dota_hero_troll_warlord",
        "name_formatted" => "Troll Warlord",
        "pic" => "troll-warlord",
        "pic_1" => "archive/troll-warlord-old-1",
        "pic_retro" => "archive/troll-warlord-old-1",
    ),
    96 => array(
        "name_raw" => "npc_dota_hero_centaur",
        "name_formatted" => "Centaur Warrunner",
        "pic" => "centaur-warrunner",
        "pic_1" => "archive/centaur-warrunner-old-1",
        "pic_2" => "archive/centaur-warrunner-old-2",
        "pic_retro" => "archive/centaur-warrunner-old-2",
    ),
    97 => array(
        "name_raw" => "npc_dota_hero_magnataur",
        "name_formatted" => "Magnus",
        "pic" => "magnus",
    ),
    98 => array(
        "name_raw" => "npc_dota_hero_shredder",
        "name_formatted" => "Timbersaw",
        "pic" => "timbersaw",
    ),
    99 => array(
        "name_raw" => "npc_dota_hero_bristleback",
        "name_formatted" => "Bristleback",
        "pic" => "bristleback",
    ),
    100 => array(
        "name_raw" => "npc_dota_hero_tusk",
        "name_formatted" => "Tusk",
        "pic" => "tusk",
        "pic_1" => "archive/tusk-old-1",
        "pic_retro" => "archive/tusk-old-1",
    ),
    101 => array(
        "name_raw" => "npc_dota_hero_skywrath_mage",
        "name_formatted" => "Skywrath Mage",
        "pic" => "skywrath-mage",
    ),
    102 => array(
        "name_raw" => "npc_dota_hero_abaddon",
        "name_formatted" => "Abaddon",
        "pic" => "abaddon",
        "pic_1" => "archive/abaddon-old-1",
        "pic_retro" => "archive/abaddon-old-1",
    ),
    103 => array(
        "name_raw" => "npc_dota_hero_elder_titan",
        "name_formatted" => "Elder Titan",
        "pic" => "elder-titan",
        "pic_1" => "archive/elder-titan-old-1",
        "pic_2" => "archive/elder-titan-old-2",
        "pic_retro" => "archive/elder-titan-old-2",
    ),
    104 => array(
        "name_raw" => "npc_dota_hero_legion_commander",
        "name_formatted" => "Legion Commander",
        "pic" => "legion-commander",
        "pic_1" => "archive/legion-commander-old-1",
        "pic_2" => "archive/legion-commander-old-2",
        "pic_retro" => "archive/legion-commander-old-2",
    ),
    105 => array(
        "name_raw" => "npc_dota_hero_techies",
        "name_formatted" => "Techies",
        "pic" => "techies",
        "pic_1" => "archive/techies-old-1",
        "pic_retro" => "archive/techies-old-1",
    ),
    106 => array(
        "name_raw" => "npc_dota_hero_ember_spirit",
        "name_formatted" => "Ember Spirit",
        "pic" => "ember-spirit",
        "pic_1" => "archive/ember-spirit-old-1",
        "pic_2" => "archive/ember-spirit-old-2",
        "pic_retro" => "archive/ember-spirit-old-2",
    ),
    107 => array(
        "name_raw" => "npc_dota_hero_earth_spirit",
        "name_formatted" => "Earth Spirit",
        "pic" => "earth-spirit",
        "pic_1" => "archive/earth-spirit-old-1",
        "pic_retro" => "archive/earth-spirit-old-1",
    ),
    108 => array(
        "name_raw" => "npc_dota_hero_abyssal_underlord",
        "name_formatted" => "Abyssal Underlord",
        "pic" => "underlord",
    ),
    109 => array(
        "name_raw" => "npc_dota_hero_terrorblade",
        "name_formatted" => "Terrorblade",
        "pic" => "terrorblade",
    ),
    110 => array(
        "name_raw" => "npc_dota_hero_phoenix",
        "name_formatted" => "Phoenix",
        "pic" => "phoenix",
    ),
    111 => array(
        "name_raw" => "npc_dota_hero_oracle",
        "name_formatted" => "Oracle",
        "pic" => "oracle",
    ),
    112 => array(
        "name_raw" => "npc_dota_hero_winter_wyvern",
        "name_formatted" => "Winter Wyvern",
        "pic" => "winter-wyvern",
        "pic_1" => "archive/winter-wyvern-old-1",
        "pic_retro" => "archive/winter-wyvern-old-1",
    ),
    113 => array(
        "name_raw" => "npc_dota_hero_arc_warden",
        "name_formatted" => "Arc Warden",
        "pic" => "arc-warden",
        "pic_1" => "archive/arc-warden-old-1",
        "pic_2" => "archive/arc-warden-old-2",
        "pic_retro" => "archive/arc-warden-old-2",
    ),
    114 => array(
        "name_raw" => "npc_dota_hero_monkey_king",
        "name_formatted" => "Monkey King",
        "pic" => "monkey-king",
    ),
    119 => array(
        "name_raw" => "npc_dota_hero_dark_willow",
        "name_formatted" => "Dark Willow",
        "pic" => "dark-willow",
    ),
    120 => array(
        "name_raw" => "npc_dota_hero_pangolier",
        "name_formatted" => "Pangolier",
        "pic" => "pangolier",
    ),
    121 => array(
        "name_raw" => "npc_dota_hero_grimstroke",
        "name_formatted" => "Grimstroke",
        "pic" => "grimstroke",
    ),
);